spring:
  profiles:
    active: pat
token:
  github:
    token:
---
spring:
  profiles: pat
  datasource:
    url: jdbc:h2:/tmp/h2
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
website:
  url: https://mycov.pat-edu.org
---
spring:
  profiles: cloud
  datasource:
    url: jdbc:h2:/tmp/mycov
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
website:
  url:
